name: Docs

on:
  push:
    branches: 
      - master
      - release/*
  pull_request:
    branches: 
      - master

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: npm install and npm run docs
      run: |
        npm install
        npm run docs
    - name: Commit files
      run: |
        git config --local user.email "doc.generator3000@github.com"
        git config --local user.name "DocGenerator 3000"
        cd docs
        git add .
        git commit -m "[Doc] - Update API documentation." 
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
